### ISSUE TITLE
Unhandled rejection Error: Cannot switch to old mode now.

### ISSUE THREAD

**Issue by stevenvachon** [Woorank/robots-txt-parse#2]
in Node 0.10
later versions are fine

I'm using this package with [bhttp](https://npmjs.com/bhttp).

**Comment by Janpot** [comment]
[our tests pass on 0.10](https://travis-ci.org/Woorank/robots-txt-parse/builds/56615721)
Can you provide a complete stacktrace? or add a failing test?
you could also try to require [readable-stream](https://www.npmjs.com/package/readable-stream) in your code

**Comment by stevenvachon** [comment]
Scroll down to the bottom of this page for a stacktrace: https://travis-ci.org/stevenvachon/broken-link-checker/jobs/94547592

**Comment by Janpot** [comment]
@stevenvachon Does using the `readable-stream` module change anything?

**Comment by stevenvachon** [comment]
Here's a comment from the bhttp dev:

> This may be an issue with Node streams themselves - I've had trouble with `pause` and `resume` in certain 0.10.x versions, which led me to implementing [this patch](https://github.com/joepie91/node-bhttp/commit/965889ee3b5ad9bcb5a3badefeb23b461da87966) internally (replacing `pause` with a pipe to the `dev-null` module).
> 
> Your application is erroring out at [this line](https://github.com/joepie91/node-bhttp/blob/f6cd01499bcf8ff5c0fe2efd44cb9f29693737b1/lib/bhttp.coffee#L498), triggered by [this line](https://github.com/Woorank/robots-txt-parse/blob/master/lib/parse.js#L110) in `robots-txt-parse`, which calls the original `resume` method on the stream. I can't really see anything in bhttp that would cause that kind of behaviour.
> 
> To me, it looks like the issue is with unavailability of `resume` in (some) 0.10 versions of Node, and that's an issue that can only be worked around by the authors of `robots-txt-parse`.

**Comment by Janpot** [comment]
@stevenvachon I published a new version. Could you try this out?

**Comment by stevenvachon** [comment]
Just pushed a new beta (not published, though) and it passed all tests, including the problematic Node 0.10

Thank you! :+1:
